name: Generate next version

on:
  workflow_call:
    outputs:
      next:
        description: "The next version number in x.y.z notation"
        value: ${{ jobs.next_version.outputs.next }}
    secrets:
      token:
        required: true
    
jobs:
  version:
    uses: ./.github/workflows/latest_version.yml
    secrets: 
      token: ${{ secrets.token }}

  next_version:
      runs-on: ubuntu-latest
      needs: version
      steps:
        - id: next
          run: |
            latest=${{ needs.version.outputs.latest }}
            major=$(echo $latest | awk -F '.' '{print $1}' )
            normal=$(echo $latest | awk -F '.' '{print $2}' )
            minor=$(echo $latest | awk -F '.' '{print $3}' )
            
            tags=(${{join(github.event.pull_request.labels.*.name, ' ')}})
            if [[ "${tags[*]}" =~ 'Major' ]]; then
              next=$((1 + major)).0.0
            elif [[ "${tags[*]}" =~ 'Minor' ]]; then
              next=$major.$normal.$((1 + minor))
            else 
              next=$major.$((1 + normal)).0
            fi

            echo "next=$next" >> $GITHUB_OUTPUT

      outputs:
        next: ${{steps.next.outputs.next}}